package com.altheria.mobile;

import android.app.*;
import android.os.Bundle;
import android.graphics.Color;
import android.graphics.Typeface;
import android.content.DialogInterface;
import android.view.*;
import android.widget.*;
import java.util.*;

public class MainActivity extends Activity {
    private AppData data; private GameSession session; private LinearLayout root; private TextView title, status, body, message; private LinearLayout actions;
    private final int BG=Color.rgb(18,17,15), PANEL=Color.rgb(33,30,25), TEXT=Color.rgb(239,231,211), MUTED=Color.rgb(181,170,150), GOLD=Color.rgb(206,170,85);
    @Override public void onCreate(Bundle b){super.onCreate(b);getWindow().setStatusBarColor(BG);getWindow().setNavigationBarColor(BG);AppData.init(this);SaveService.init(this);try{data=new AppData();}catch(Exception e){showFatal(e.getMessage());return;}showMenu();}
    private TextView tv(String s,int sp,boolean bold){TextView t=new TextView(this);t.setText(s);t.setTextColor(TEXT);t.setTextSize(sp);t.setPadding(18,12,18,12);if(bold)t.setTypeface(Typeface.DEFAULT,Typeface.BOLD);return t;}
    private Button btn(String s){Button b=new Button(this);b.setText(s);b.setTextColor(TEXT);b.setTextSize(15);b.setAllCaps(false);b.setBackgroundColor(PANEL);b.setPadding(12,10,12,10);return b;}
    private ScrollView wrap(View v){ScrollView sc=new ScrollView(this);sc.setFillViewport(true);sc.addView(v);return sc;}
    private void base(String heading){root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(12,12,12,16);root.setBackgroundColor(BG);title=tv(heading,24,true);title.setTextColor(GOLD);root.addView(title);status=tv("",14,false);status.setTextColor(MUTED);root.addView(status);body=tv("",16,false);root.addView(body,new LinearLayout.LayoutParams(-1,0,1));actions=new LinearLayout(this);actions.setOrientation(LinearLayout.VERTICAL);root.addView(actions);setContentView(wrap(root));}
    private void addAction(String label, View.OnClickListener l){Button b=btn(label);b.setOnClickListener(l);actions.addView(b,new LinearLayout.LayoutParams(-1,ViewGroup.LayoutParams.WRAP_CONTENT));}
    private void updateHeader(){if(session==null||session.player==null){status.setText("");return;}Models.Player p=session.player;status.setText(p.name+"  •  Dia "+p.day+"  •  Lv "+p.level+"  •  HP "+p.hp+"/"+p.maxHp+"  •  Ouro "+p.gold+"\n"+"🍖 Fome "+p.hunger+"/100  •  💧 Sede "+p.thirst+"/100  •  "+p.realm+" / "+p.city+"  •  "+p.lifePath+ (p.nature.isBlank()?"":"  •  Elyth: "+p.nature));}
    private void showMenu(){base("ALTHERIA");body.setText("Adventure — RPG narrativo de Altheria\n\n7.880 eventos • 1.000 habilidades Elyth • 1.000 feitiços • 3.600 monstros • 1.200 Renegados • 4.280+ NPCs\n\n3.000 conquistas • 1.200 desfechos de Prólogo • 22.000 interações sociais\n\nEscolha como sua vida começa.");addAction("Nova jornada",v->newGame());addAction("Continuar",v->load());addAction("Codex",v->codex());}
    private void newGame(){final String[] paths={"Aventureiro","Valaryn","Mago"};new AlertDialog.Builder(this).setTitle("Caminho de vida").setItems(paths,(d,w)->selectRealm(paths[w])).show();}
    private void selectRealm(String pathName){Models.LifePath path=pathName.equals("Valaryn")?Models.LifePath.VALARYN:pathName.equals("Aventureiro")?Models.LifePath.ADVENTURER:Models.LifePath.INDEPENDENT;final String[] realms=data.realms.toArray(new String[0]);new AlertDialog.Builder(this).setTitle("Reino de origem").setItems(realms,(d,w)->selectCity(path,realms[w])).show();}
    private void selectCity(Models.LifePath path,String realm){List<String> cities=data.citiesByRealm.getOrDefault(realm,new ArrayList<>());if(cities.isEmpty()){startGame(path,realm,"Valdora");return;}String[] a=cities.toArray(new String[0]);new AlertDialog.Builder(this).setTitle("Cidade de origem — "+realm).setItems(a,(d,w)->startGame(path,realm,a[w])).show();}
    private void startGame(Models.LifePath path,String realm,String city){final EditText e=new EditText(this);e.setHint("Nome do personagem");e.setTextColor(TEXT);new AlertDialog.Builder(this).setTitle("Nome").setView(e).setPositiveButton("Começar",(d,w)->{session=new GameSession(data);session.startNew(e.getText().toString(),path,realm,city,path==Models.LifePath.VALARYN?"Estudante":path==Models.LifePath.INDEPENDENT?"Mago":"Aventureiro","Sonhador",18);showAdventure();}).setNegativeButton("Cancelar",null).show();}
    private void showAdventure(){base(session!=null&&session.combat!=null?"COMBATE":"ALTHERIA — AVENTURA");if(session.combat!=null){showCombat();return;}updateHeader();Models.Event ev=session.current;if(ev==null){body.setText("Nenhum evento elegível.\n\n"+session.message);return;}body.setText("【"+ev.title()+"】\n\n"+ev.text()+"\n\n"+session.message);addAction("1 — "+ev.choice1().text(),v->{session.choose(1);showAdventure();});if(ev.choice2()!=null&&!ev.choice2().text().isBlank())addAction("2 — "+ev.choice2().text(),v->{session.choose(2);showAdventure();});addAction("🎒 Inventário",v->inventory());addAction("⚔ Guilda / Caçadas",v->guild());addAction("🗺 Viagem / Transporte",v->travel());addAction("👥 Relações",v->relations());addAction("🏛 Locais",v->places());addAction("🏆 Prólogo / Conquistas",v->prologue());addAction("✨ Habilidades",v->skills());addAction("📖 Magia",v->magic());addAction("⚔ Arena",v->{session.startArena();showAdventure();});addAction("🏰 Dungeon",v->dungeon());addAction("😴 Descansar",v->{session.rest();showAdventure();});addAction("💾 Salvar",v->save());addAction("☰ Menu",v->showMenu());}
    private void showCombat(){base("COMBATE");updateHeader();CombatEngine.CombatState c=session.combat;StringBuilder s=new StringBuilder();s.append("Inimigo: ").append(c.enemy.name()).append("\nHP: ").append(c.enemyHp).append("/").append(c.enemy.hp()).append("\n\n");for(String line:c.log)s.append(line).append('\n');body.setText(s.toString());addAction("Atacar",v->{session.combatEngine.attack(session);showAdventure();});addAction("Defender",v->{session.combatEngine.defend(session);showAdventure();});addAction("Técnica",v->{session.combatEngine.technique(session);showAdventure();});addAction("Magia",v->{session.combatEngine.magic(session);showAdventure();});addAction("Usar item",v->{session.combatEngine.useItem(session);showAdventure();});addAction("Fugir",v->{session.combatEngine.flee(session);showAdventure();});}
    private void inventory(){final List<Models.Item> items=new ArrayList<>();final List<String> labels=new ArrayList<>();for(String id:session.player.inventory.keySet()){Models.Item i=data.itemById.get(id);if(i!=null){items.add(i);labels.add(i.name()+" ×"+session.player.itemCount(id)+" — "+itemEffectLabel(i));}}if(labels.isEmpty()){toast("Inventário vazio.");return;}new AlertDialog.Builder(this).setTitle("Inventário").setItems(labels.toArray(new String[0]),(d,w)->{Models.Item i=items.get(w);if(i.consumable()){session.useItem(i.id());}else{session.equipItem(i.id());}showAdventure();}).setNegativeButton("Fechar",null).show();}
    private String itemEffectLabel(Models.Item i){StringBuilder b=new StringBuilder();if(i.hunger()>0)b.append("Fome+").append(i.hunger()).append(" ");if(i.thirst()>0)b.append("Sede+").append(i.thirst()).append(" ");if(i.heal()>0)b.append("HP+").append(i.heal()).append(" ");if(i.mana()>0)b.append("Mana+").append(i.mana()).append(" ");if(i.attack()>0)b.append("ATQ+").append(i.attack()).append(" ");if(i.defense()>0)b.append("DEF+").append(i.defense()).append(" ");String x=b.toString().trim();return x.isBlank()?"item":x;}
    private void guild(){if(session.hasActiveHunt()){new AlertDialog.Builder(this).setTitle("Caçada ativa").setMessage(session.activeHuntSummary()).setPositiveButton("Investigar pistas",(d,w)->{session.gatherHuntIntel();showAdventure();}).setNeutralButton("Partir",(d,w)->{session.launchActiveHunt();showAdventure();}).setNegativeButton("Fechar",null).show();return;}String[] board={"Caçar monstros","Caçar Renegados","Quest da Guilda","Formar grupo"};new AlertDialog.Builder(this).setTitle("Guilda").setItems(board,(d,w)->{if(w==0)monsterHunt();else if(w==1)renegadeHunt();else if(w==2)quest();else party();}).show();}
    private void party(){List<Models.Npc> ns=session.nearbyNpcs();if(ns.isEmpty()){toast("Nenhum aventureiro disponível aqui.");return;}String[] a=new String[Math.min(20,ns.size())];for(int i=0;i<a.length;i++){Models.Npc n=ns.get(i);a[i]=n.name()+" — "+n.role()+" — "+n.gender();}new AlertDialog.Builder(this).setTitle("Formar grupo — "+session.player.partyMembers.size()+"/4").setItems(a,(d,w)->{session.recruitPartyMember(ns.get(w).id());showAdventure();}).show();}
    private void monsterHunt(){List<Models.Monster> ms=session.guildOffers();if(ms.isEmpty()){toast("Nenhum contrato disponível.");return;}String[] a=new String[ms.size()];for(int i=0;i<a.length;i++){Models.Monster m=ms.get(i);a[i]=m.name()+" — ameaça "+m.threatClass();}new AlertDialog.Builder(this).setTitle("Caçada de monstros").setItems(a,(d,w)->{session.acceptMonsterHunt(ms.get(w),"ELIMINATE");showAdventure();}).show();}
    private void renegadeHunt(){List<Models.Renegade> rs=session.guildRenegadeOffers();if(rs.isEmpty()){toast("Nenhum Renegado compatível com seu rank nesta região.");return;}String[] a=new String[rs.size()];for(int i=0;i<a.length;i++){Models.Renegade r=rs.get(i);a[i]=r.name()+" — Rank "+r.rank()+" — "+r.approxLocation();}new AlertDialog.Builder(this).setTitle("Renegados mapeados").setItems(a,(d,w)->{session.acceptRenegadeHunt(rs.get(w),"ELIMINATE");showAdventure();}).show();}
    private void quest(){List<Models.Monster> ms=session.guildOffers();if(ms.isEmpty()){toast("Nenhuma quest disponível.");return;}Models.Monster m=ms.get(0);session.acceptGuildQuest(m);showAdventure();}
    private void travel(){List<Models.Route> rs=session.nearbyRoutes();if(rs.isEmpty()){toast("Não há rota registrada daqui.");return;}String[] a=new String[rs.size()];for(int i=0;i<a.length;i++){Models.Route r=rs.get(i);String to=r.from().equals(session.player.city)?r.to():r.from();a[i]=to+" — "+r.days()+"d — "+r.cost()+" ouro";}new AlertDialog.Builder(this).setTitle("Viagem").setItems(a,(d,w)->{Models.Route r=rs.get(w);String to=r.from().equals(session.player.city)?r.to():r.from();session.travelTo(to);showAdventure();}).setNeutralButton("Transportes",(d,w)->transport()).show();}
    private void transport(){List<Models.Transport> ts=new ArrayList<>(session.transportOptions());if(ts.isEmpty()){toast("Nenhum transporte disponível para compra.");return;}String[] a=new String[ts.size()];for(int i=0;i<a.length;i++){Models.Transport t=ts.get(i);a[i]=t.name()+" — "+t.cost()+" ouro — velocidade "+t.speed();}new AlertDialog.Builder(this).setTitle("Transportes").setItems(a,(d,w)->{session.buyTransport(ts.get(w).id());showAdventure();}).show();}
    private void relations(){List<Models.Npc> ns=session.nearbyNpcs();if(ns.isEmpty()){toast("Nenhum NPC relevante aqui.");return;}String[] a=new String[Math.min(ns.size(),25)];for(int i=0;i<a.length;i++){Models.Npc n=ns.get(i);a[i]=n.name()+" — "+n.role()+" — relação "+session.player.relation(n.id());}new AlertDialog.Builder(this).setTitle("Pessoas ao redor").setItems(a,(d,w)->{Models.Npc n=ns.get(w);String[] act={"Conversar","Fazer amizade","Tentar romance","Propor casamento","Procurar pessoa"};new AlertDialog.Builder(this).setTitle(n.name()).setItems(act,(d2,k)->{if(k==0)session.talkToNpc(n.id());else if(k==1)session.befriendNpc(n.id());else if(k==2)session.startRomance(n.id());else if(k==3)session.marryNpc(n.id());else session.searchForNpc(n.id());showAdventure();}).show();}).show();}
    private void skills(){List<Models.Ability> ls=session.learnableSkills();if(ls.isEmpty()){toast("Sem habilidades disponíveis com seus requisitos atuais.");return;}String[] a=new String[ls.size()];for(int i=0;i<a.length;i++){Models.Ability x=ls.get(i);a[i]=x.name()+" — T"+x.tier()+" — "+x.category();}new AlertDialog.Builder(this).setTitle("Habilidades — pontos "+session.player.skillPoints).setItems(a,(d,w)->{session.learnSkill(ls.get(w).id());showAdventure();}).show();}
    private void magic(){List<Models.Spell> ls=session.learnableSpells();String[] a=new String[ls.size()+10];for(int i=0;i<ls.size();i++){Models.Spell x=ls.get(i);a[i]=x.name()+" — T"+x.tier()+" — Mana "+x.mana();}for(int i=1;i<=10;i++)a[ls.size()+i-1]="📖 Estudar grimório do "+i+"º círculo";new AlertDialog.Builder(this).setTitle("Magia — pontos "+session.player.skillPoints).setItems(a,(d,w)->{if(w<ls.size())session.learnSpell(ls.get(w).id());else session.studyGrimoire(w-ls.size()+1);showAdventure();}).show();}
    private void dungeon(){List<Models.Dungeon> ds=new ArrayList<>();for(Models.Dungeon d:data.dungeons)if(d.city().equals(session.player.city))ds.add(d);if(ds.isEmpty()){toast("Nenhuma Dungeon registrada nesta cidade.");return;}String[] a=new String[ds.size()];for(int i=0;i<a.length;i++){Models.Dungeon d=ds.get(i);a[i]=d.name()+" — "+d.maxFloor()+" andares — entrada "+d.entryCost();}new AlertDialog.Builder(this).setTitle("Dungeons").setItems(a,(d,w)->{session.enterDungeon(ds.get(w));showAdventure();}).show();}
    private void save(){try{SaveService.save(session.player);toast("Jornada salva neste aparelho.");}catch(Exception e){toast("Erro ao salvar: "+e.getMessage());}}
    private void load(){try{session=new GameSession(data,SaveService.load());Models.Event e=data.eventById.get(session.player.currentEventId);session.current=(e!=null&&session.engine.eligible(e,session.player))?e:session.engine.next(session.player);showAdventure();}catch(Exception e){toast(e.getMessage());}}
    private void places(){List<Models.Location> ls=session.currentLocations();if(ls.isEmpty()){toast("Nenhum local registrado.");return;}String[] a=new String[ls.size()];for(int i=0;i<a.length;i++){Models.Location x=ls.get(i);a[i]=x.name()+" — "+x.kind();}new AlertDialog.Builder(this).setTitle("Locais acessíveis — "+session.player.city).setItems(a,(d,w)->{Models.Location x=ls.get(w);toast(x.description()+"\nHorário: "+x.hours());}).show();}
    private void prologue(){base("PRÓLOGO");StringBuilder b=new StringBuilder();b.append("Conquistas registradas: ").append(session.player.achievements.size()).append("/3000\n\n");for(String id:session.player.prologue){Models.Prologue e=data.prologueById.get(id);if(e!=null)b.append("• ").append(e.title()).append("\n").append(e.text()).append("\n\n");}if(session.player.prologue.isEmpty())b.append("Ainda não há desfechos registrados. Suas decisões produzirão registros aqui.");body.setText(b.toString());addAction("Voltar",v->showAdventure());}
    private void codex(){base("CODEX");body.setText("ALTHERIA\n\nItens: "+data.items.size()+"\nReinos: "+data.realms.size()+"\nCidades: "+data.cities.size()+"\nEventos: "+data.events.size()+"\nNaturezas Elyth: "+data.natureNames.size()+"\nHabilidades Elyth: "+data.elythAbilities.size()+"\nFeitiços: "+data.spells.size()+"\nMonstros: "+data.monsters.size()+"\nFauna: "+data.fauna.size()+"\nRenegados: "+data.renegades.size()+"\nNPCs: "+data.npcs.size()+"\nTransportes: "+data.transports.size()+"\n\nAs três vias de poder são Elyth, Vellum e Magia/Mana; Bênçãos são uma via religiosa distinta.\n\nValaryn: Calouro → Aprendiz → Aspirante → Cadete F → E → D → C → B → A → S → Z");addAction("Voltar",v->showMenu());}
    private void toast(String s){Toast.makeText(this,s,Toast.LENGTH_LONG).show();}
    private void showFatal(String s){new AlertDialog.Builder(this).setTitle("ALTHERIA").setMessage(s).setCancelable(false).setPositiveButton("Fechar",(d,w)->finish()).show();}
}
