package com.altheria.mobile;

import android.content.Context;
import android.content.SharedPreferences;
import java.io.*;
import java.util.*;

final class SaveService {
    private static Context context;
    private static final String PREFS="altheria_save_v1";
    private SaveService(){}
    static void init(Context c){context=c.getApplicationContext();}
    static void save(Models.Player p)throws IOException{if(context==null)throw new IOException("SaveService não inicializado.");SharedPreferences x=context.getSharedPreferences(PREFS,Context.MODE_PRIVATE);Map<String,String> m=new LinkedHashMap<>();put(m,"version","5");put(m,"name",p.name);put(m,"lifePath",p.lifePath.name());put(m,"realm",p.realm);put(m,"city",p.city);put(m,"profession",p.profession);put(m,"background",p.background);put(m,"age",p.age);put(m,"currentEventId",p.currentEventId);put(m,"level",p.level);put(m,"xp",p.xp);put(m,"hp",p.hp);put(m,"maxHp",p.maxHp);put(m,"gold",p.gold);put(m,"reputation",p.reputation);put(m,"fatigue",p.fatigue);put(m,"day",p.day);put(m,"academyDay",p.academyDay);put(m,"vellumArmorial",p.vellumArmorial);put(m,"vellumMartial",p.vellumMartial);put(m,"mana",p.mana);put(m,"maxMana",p.maxMana);put(m,"skillPoints",p.skillPoints);put(m,"guildRank",p.guildRank);put(m,"guildRep",p.guildRep);put(m,"arenaRating",p.arenaRating);put(m,"arenaWins",p.arenaWins);put(m,"arenaLosses",p.arenaLosses);put(m,"dungeonFloor",p.dungeonFloor);put(m,"childrenCount",p.childrenCount);put(m,"huntIntel",p.huntIntel);put(m,"huntIntelRequired",p.huntIntelRequired);put(m,"nature",p.nature);put(m,"activeDungeon",p.activeDungeon);put(m,"activeTransportId",p.activeTransportId);put(m,"activeHuntType",p.activeHuntType);put(m,"activeHuntTargetId",p.activeHuntTargetId);put(m,"activeHuntMode",p.activeHuntMode);put(m,"spouseId",p.spouseId);
        SharedPreferences.Editor e=x.edit();e.clear();for(var z:m.entrySet())e.putString(z.getKey(),z.getValue());e.putString("flags",joinSet(p.flags));e.putString("achievements",joinSet(p.achievements));e.putString("partyMembers",joinSet(p.partyMembers));e.putString("prologue",joinList(p.prologue));e.putString("seen",joinSet(p.seenEvents));e.putString("abilities",joinSet(p.abilities));e.putString("spells",joinSet(p.spells));e.putString("discoveredCities",joinSet(p.discoveredCities));e.putString("completedQuests",joinSet(p.completedQuests));e.putString("ownedTransports",joinSet(p.ownedTransports));e.putString("childrenNames",joinSet(p.childrenNames));e.putString("hunger",String.valueOf(p.hunger));e.putString("thirst",String.valueOf(p.thirst));e.putString("stats",encodeMap(p.stats));e.putString("relations",encodeMap(p.relations));e.putString("inventory",encodeMap(p.inventory));e.putString("history",encodeMap(p.eventHistory));e.putString("equipment",encodeStringMap(p.equipment));e.putString("cityStability",encodeMap(p.cityStability));e.putString("cityEconomy",encodeMap(p.cityEconomy));e.putString("cityThreat",encodeMap(p.cityThreat));e.putString("relationshipStages",encodeStringMap(p.relationshipStages));e.putString("npcSearches",encodeMap(p.npcSearches));e.apply();}
    static Models.Player load()throws IOException{if(context==null)throw new IOException("SaveService não inicializado.");SharedPreferences x=context.getSharedPreferences(PREFS,Context.MODE_PRIVATE);if(!x.contains("version"))throw new FileNotFoundException("Nenhum save encontrado neste aparelho.");Models.Player p=new Models.Player();p.name=x.getString("name",p.name);try{p.lifePath=Models.LifePath.valueOf(x.getString("lifePath",p.lifePath.name()));}catch(Exception ignored){}p.realm=x.getString("realm",p.realm);p.city=x.getString("city",p.city);p.profession=x.getString("profession",p.profession);p.background=x.getString("background",p.background);p.age=i(x,"age",18);p.currentEventId=x.getString("currentEventId","");p.level=i(x,"level",1);p.xp=i(x,"xp",0);p.hp=i(x,"hp",30);p.maxHp=i(x,"maxHp",30);p.gold=i(x,"gold",40);p.reputation=i(x,"reputation",0);p.fatigue=i(x,"fatigue",0);p.hunger=i(x,"hunger",85);p.thirst=i(x,"thirst",85);p.day=i(x,"day",1);p.academyDay=i(x,"academyDay",0);p.vellumArmorial=i(x,"vellumArmorial",0);p.vellumMartial=i(x,"vellumMartial",0);p.mana=i(x,"mana",0);p.maxMana=i(x,"maxMana",0);p.skillPoints=i(x,"skillPoints",0);p.guildRank=i(x,"guildRank",0);p.guildRep=i(x,"guildRep",0);p.arenaRating=i(x,"arenaRating",1000);p.arenaWins=i(x,"arenaWins",0);p.arenaLosses=i(x,"arenaLosses",0);p.dungeonFloor=i(x,"dungeonFloor",0);p.childrenCount=i(x,"childrenCount",0);p.huntIntel=i(x,"huntIntel",0);p.huntIntelRequired=i(x,"huntIntelRequired",0);p.nature=x.getString("nature","");p.activeDungeon=x.getString("activeDungeon","");p.activeTransportId=x.getString("activeTransportId","");p.activeHuntType=x.getString("activeHuntType","");p.activeHuntTargetId=x.getString("activeHuntTargetId","");p.activeHuntMode=x.getString("activeHuntMode","");p.spouseId=x.getString("spouseId","");splitSet(x.getString("flags",""),p.flags);splitSet(x.getString("achievements",""),p.achievements);splitSet(x.getString("partyMembers",""),p.partyMembers);p.prologue.clear();p.prologue.addAll(splitList(x.getString("prologue","")));splitSet(x.getString("seen",""),p.seenEvents);splitSet(x.getString("abilities",""),p.abilities);splitSet(x.getString("spells",""),p.spells);splitSet(x.getString("discoveredCities",""),p.discoveredCities);splitSet(x.getString("completedQuests",""),p.completedQuests);splitSet(x.getString("ownedTransports",""),p.ownedTransports);splitSet(x.getString("childrenNames",""),p.childrenNames);decodeMap(x.getString("stats",""),p.stats);decodeMap(x.getString("relations",""),p.relations);decodeMap(x.getString("inventory",""),p.inventory);decodeMap(x.getString("history",""),p.eventHistory);decodeStringMap(x.getString("equipment",""),p.equipment);decodeMap(x.getString("cityStability",""),p.cityStability);decodeMap(x.getString("cityEconomy",""),p.cityEconomy);decodeMap(x.getString("cityThreat",""),p.cityThreat);decodeStringMap(x.getString("relationshipStages",""),p.relationshipStages);decodeMap(x.getString("npcSearches",""),p.npcSearches);return p;}
    private static void put(Map<String,String> m,String k,Object v){m.put(k,String.valueOf(v));}private static int i(SharedPreferences x,String k,int d){try{return Integer.parseInt(x.getString(k,String.valueOf(d)));}catch(Exception e){return d;}}private static String joinSet(Set<String>s){return String.join("|",s);}
    private static String joinList(List<String>s){return String.join("|",s);}
    private static List<String> splitList(String s){return s==null||s.isBlank()?new ArrayList<>():new ArrayList<>(Arrays.asList(s.split("\\|")));}private static String encodeMap(Map<String,Integer>m){StringBuilder b=new StringBuilder();for(var e:m.entrySet()){if(b.length()>0)b.append('|');b.append(e.getKey()).append(':').append(e.getValue());}return b.toString();}private static String encodeStringMap(Map<String,String>m){StringBuilder b=new StringBuilder();for(var e:m.entrySet()){if(b.length()>0)b.append('|');b.append(e.getKey()).append('~').append(e.getValue());}return b.toString();}private static void decodeMap(String s,Map<String,Integer>m){if(s==null||s.isBlank())return;for(String a:s.split("\\|")){String[]p=a.split(":",2);if(p.length==2)try{m.put(p[0],Integer.parseInt(p[1]));}catch(Exception ignored){}}}private static void decodeStringMap(String s,Map<String,String>m){if(s==null||s.isBlank())return;for(String a:s.split("\\|")){String[]p=a.split("~",2);if(p.length==2)m.put(p[0],p[1]);}}private static void splitSet(String s,Set<String>set){if(s==null||s.isBlank())return;set.addAll(Arrays.asList(s.split("\\|")));}
}
